server:
  port: 9001                   # mapper映射文件
spring:
  application:
    name: proe

eureka:
  client:   #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: hystrix9001
    prefer-ip-address: true       #访问路径可以显示ip地址

info:
  app.name: cloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

